/**
 * Styles for DatabaseBrowserLayout and its sub-components
 */

import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    content: {
        flex: 1,
        flexDirection: 'row',
    },
    sidebar: {
        width: 200,
        borderRightWidth: 1,
        borderRightColor: '#e0e0e0',
        backgroundColor: '#fafafa',
        position: 'relative',
    },
    sidebarCollapseHandle: {
        position: 'absolute',
        right: -12,
        top: 0,
        bottom: 0,
        width: 12,
        zIndex: 10,
        justifyContent: 'center',
        alignItems: 'center',
        cursor: 'pointer',
    },
    collapseHandleBars: {
        flexDirection: 'row',
        gap: 2,
        alignItems: 'center',
    },
    collapseHandleBar: {
        width: 2,
        height: 20,
        backgroundColor: '#667eea',
        borderRadius: 1,
    },
    databaseDropdownRow: {
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        backgroundColor: '#dddfff',
        minHeight: 65,
    },
    databaseDropdownButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        justifyContent: 'space-between',
    },
    databaseDropdownContent: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
    },
    databaseDropdownText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
    },
    databaseDropdownSubtext: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    databaseDropdownIcon: {
        fontSize: 10,
        color: '#666',
        marginLeft: 8,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
        justifyContent: 'flex-start',
        paddingTop: 48,
        paddingLeft: 0,
    },
    dropdownContainer: {
        backgroundColor: '#fff',
        borderRightWidth: 1,
        borderRightColor: '#e0e0e0',
        width: 200,
        maxHeight: '80%',
        shadowColor: '#000',
        shadowOffset: { width: 2, height: 0 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 5,
    },
    dropdownScroll: {
        maxHeight: 400,
    },
    dropdownItem: {
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    dropdownItemSelected: {
        backgroundColor: '#e8f0ff',
    },
    dropdownItemText: {
        fontSize: 14,
        color: '#333',
    },
    dropdownItemTextSelected: {
        color: '#667eea',
        fontWeight: '600',
    },
    tableList: {
        flex: 1,
    },
    sectionHeader: {
        padding: 8,
        paddingLeft: 12,
        paddingTop: 12,
        paddingRight: 12,
        backgroundColor: '#f0f0f0',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    sectionHeaderText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#666',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        flex: 1,
    },
    sectionHeaderIcon: {
        fontSize: 10,
        color: '#666',
        marginLeft: 8,
    },
    tableItem: {
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        maxHeight: 36
    },
    tableItemEmpty: {
        opacity: 0.5,
        backgroundColor: '#f9f9f9',
    },
    tableItemSelected: {
        backgroundColor: '#667eea',
        opacity: 1,
    },
    tableItemContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
    },
    tableItemText: {
        fontSize: 14,
        color: '#333',
        flex: 1,
    },
    tableItemTextEmpty: {
        color: '#999',
        fontStyle: 'italic',
    },
    tableItemTextSelected: {
        color: '#fff',
        fontWeight: '500',
        fontStyle: 'normal',
    },
    tableItemCount: {
        fontSize: 12,
        color: '#666',
        marginLeft: 8,
    },
    tableItemCountEmpty: {
        color: '#bbb',
    },
    tableItemCountSelected: {
        color: '#fff',
        opacity: 0.8,
    },
    mainContent: {
        flex: 1,
        backgroundColor: '#fff',
        flexDirection: 'column',
    },
    centeredContent: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    centeredDropdownContainer: {
        width: 300,
        maxWidth: '80%',
    },
    centeredDropdownButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#f5f5f5',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        justifyContent: 'space-between',
    },
    centeredModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    centeredDropdownListContainer: {
        backgroundColor: '#fff',
        borderRadius: 8,
        width: 300,
        maxWidth: '80%',
        maxHeight: '60%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 8,
    },
    connectionOptionsScroll: {
        flex: 1,
        width: '100%',
    },
    connectionOptionsContainer: {
        padding: 20,
        alignItems: 'center',
        maxWidth: 500,
        width: '100%',
        alignSelf: 'center',
    },
    connectionTitle: {
        fontSize: 24,
        fontWeight: '600',
        marginBottom: 30,
        color: '#333',
    },
    section: {
        width: '100%',
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
        marginBottom: 12,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    connectionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        backgroundColor: '#f5f5f5',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    connectionButtonText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
    },
    connectionButtonIcon: {
        fontSize: 16,
        color: '#667eea',
        fontWeight: '600',
    },
    connectionForm: {
        width: '100%',
        padding: 16,
        backgroundColor: '#fafafa',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    input: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 6,
        padding: 12,
        fontSize: 16,
        marginBottom: 12,
        color: '#333',
    },
    formButtons: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
        marginTop: 8,
    },
    formButton: {
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 6,
        minWidth: 80,
        alignItems: 'center',
    },
    formButtonCancel: {
        backgroundColor: '#f0f0f0',
    },
    formButtonSubmit: {
        backgroundColor: '#667eea',
    },
    formButtonText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#333',
    },
    formButtonTextSubmit: {
        color: '#fff',
    },
    errorText: {
        color: '#d32f2f',
        fontSize: 14,
        marginBottom: 12,
    },
    exportSection: {
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
        padding: 12,
        backgroundColor: '#fafafa',
        height: 58, // Match pagination bar height exactly (12px padding top + 12px padding bottom + 24px content = 48px)
        justifyContent: 'center',
        alignItems: 'center',
    },
    exportButton: {
        backgroundColor: '#f5f5f5',
        borderRadius: 4,
        paddingHorizontal: 12,
        paddingVertical: 6,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    exportButtonText: {
        color: '#333',
        fontSize: 12,
        fontWeight: '600',
        marginBottom: 2,
    },
    exportButtonSubtext: {
        color: '#666',
        fontSize: 10,
    },
    exportModalContent: {
        backgroundColor: '#fff',
        borderRadius: 12,
        width: '90%',
        maxWidth: 600,
        maxHeight: '80%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    exportModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    exportModalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    modalCloseButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#f5f5f5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalCloseText: {
        fontSize: 18,
        color: '#666',
        fontWeight: 'bold',
    },
    exportModalBody: {
        padding: 16,
    },
    exportModalDescription: {
        fontSize: 14,
        color: '#666',
        marginBottom: 12,
    },
    exportFormatSelector: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 20,
    },
    exportFormatButton: {
        flex: 1,
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: '#e0e0e0',
        backgroundColor: '#fafafa',
        alignItems: 'center',
    },
    exportFormatButtonSelected: {
        borderColor: '#667eea',
        backgroundColor: '#f0f4ff',
    },
    exportFormatButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
    },
    exportFormatButtonTextSelected: {
        color: '#667eea',
    },
    exportTableSelector: {
        maxHeight: 300,
    },
    exportSelectAllButton: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
        backgroundColor: '#f5f5f5',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        marginBottom: 8,
        alignItems: 'center',
    },
    exportSelectAllButtonText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#667eea',
    },
    exportTableList: {
        maxHeight: 250,
    },
    exportTableItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: '#e0e0e0',
        marginBottom: 8,
        backgroundColor: '#fafafa',
    },
    exportTableItemSelected: {
        borderColor: '#667eea',
        backgroundColor: '#f0f4ff',
    },
    exportTableCheckbox: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: '#ccc',
        marginRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    exportTableCheckboxSelected: {
        width: 10,
        height: 10,
        borderRadius: 2,
        backgroundColor: '#667eea',
    },
    exportTableItemText: {
        flex: 1,
        fontSize: 14,
        fontWeight: '500',
        color: '#333',
    },
    exportTableItemCount: {
        fontSize: 12,
        color: '#666',
        marginLeft: 8,
    },
    exportModalFooter: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
        padding: 16,
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
    },
    exportModalButton: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 6,
        minWidth: 120,
        alignItems: 'center',
    },
    exportModalCancelButton: {
        backgroundColor: '#f5f5f5',
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    exportModalDownloadButton: {
        backgroundColor: '#667eea',
    },
    exportModalButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
    },
});

