import { StyleSheet } from 'react-native';

// @ts-ignore
export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loadingContainer: {
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 14,
    color: '#666',
  },
  errorContainer: {
    backgroundColor: '#ffebee',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  errorText: {
    color: '#c62828',
    fontSize: 14,
  },
  tableContainer: {
    flex: 1,
  },
  tableScroll: {
    flex: 1,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#667eea',
    borderBottomWidth: 2,
    borderBottomColor: '#5568d3',
    maxHeight: 36,
  },
  tableHeaderCell: {
    padding: 12,
    borderRightWidth: 1,
    borderRightColor: '#5568d3',
    justifyContent: 'center',
    position: 'relative',
    maxHeight: 36,
  },
  headerCellContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  tableHeaderText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  sortIndicator: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  filterIndicator: {
    color: '#fff',
    fontSize: 12,
    marginLeft: 4,
  },
  tableBodyScroll: {
    flex: 1,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    maxHeight: 36,
  },
  tableCell: {
    padding: 10,
    borderRightWidth: 1,
    borderRightColor: '#f0f0f0',
    justifyContent: 'center',
    maxHeight: 36,
    overflow: 'visible',
  },
  tableCellText: {
    fontSize: 12,
    color: '#333',
    fontFamily: 'monospace',
    includeFontPadding: false,
  },
  tableCellTextDate: {
    fontSize: 11,
    color: '#333',
    fontFamily: 'monospace',
    includeFontPadding: false,
  },
  nullValueText: {
    color: '#bbb',
    fontStyle: 'normal',
  },
  checkboxContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 2,
    borderColor: '#ccc',
    borderRadius: 3,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    borderColor: '#667eea',
    backgroundColor: '#667eea',
  },
  checkboxCheckmark: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  colorCellContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  colorDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  urlLink: {
    color: '#0066cc',
    textDecorationLine: 'underline',
  },
  enumChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  enumChipText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '600',
  },
  numberSuffix: {
    paddingLeft: 3, // Half-space effect using padding
    color: '#888',
  },
  emptyRow: {
    padding: 20,
    alignItems: 'center',
  },
  emptyText: {
    color: '#999',
    fontSize: 14,
    fontStyle: 'italic',
  },
  pagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    backgroundColor: '#fafafa',
  },
  paginationRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  csvDownloadIconButton: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: '#f5f5f5',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  csvDownloadIconText: {
    color: '#666',
    fontSize: 16,
  },
  paginationButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#667eea',
    borderRadius: 4,
  },
  paginationButtonDisabled: {
    backgroundColor: '#ccc',
    opacity: 0.5,
  },
  paginationButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  paginationText: {
    fontSize: 14,
    color: '#666',
  },
  paginationWarning: {
    fontSize: 12,
    color: '#ff9800',
    fontStyle: 'italic',
  },
  disabledInput: {
    backgroundColor: '#f5f5f5',
    opacity: 0.6,
  },
  disabledHeader: {
    opacity: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  hiddenColumnsModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    width: '80%',
    maxWidth: 400,
    maxHeight: '70%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  hiddenColumnsModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  hiddenColumnsModalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseText: {
    fontSize: 24,
    color: '#666',
  },
  hiddenColumnsModalBody: {
    maxHeight: 400,
  },
  hiddenColumnItem: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  hiddenColumnItemText: {
    fontSize: 14,
    color: '#333',
  },
  filterModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    width: '95%',
    maxWidth: 800,
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
  },
  filterModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  filterModalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  filterModalBody: {
    padding: 20,
  },
  filterSection: {
    marginBottom: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  filterSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 16,
  },
  filterInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    padding: 12,
    fontSize: 14,
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  filterModalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  filterButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 4,
    minWidth: 80,
    alignItems: 'center',
  },
  filterApplyButton: {
    backgroundColor: '#667eea',
  },
  filterClearButton: {
    backgroundColor: '#ccc',
  },
  filterButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  filterLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
    marginBottom: 8,
    marginTop: 12,
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  filterRowLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
    marginRight: 12,
    minWidth: 70,
  },
  filterInputSmall: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    padding: 8,
    fontSize: 14,
    backgroundColor: '#fff',
    width: 100,
  },
  filterCheckboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  filterCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#667eea',
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  filterCheckboxChecked: {
    backgroundColor: '#667eea',
  },
  filterCheckboxCheckmark: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  filterCheckboxLabel: {
    fontSize: 14,
    color: '#333',
    flex: 1,
  },
  filterTypeSelector: {
    marginBottom: 16,
  },
  filterTypeButtons: {
    flexDirection: 'row',
    marginTop: 8,
  },
  filterTypeButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 4,
    backgroundColor: '#f0f0f0',
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  filterTypeButtonActive: {
    backgroundColor: '#667eea',
    borderColor: '#667eea',
  },
  filterTypeButtonText: {
    fontSize: 12,
    color: '#333',
    fontWeight: '500',
  },
  filterTypeButtonTextActive: {
    color: '#fff',
  },
  filterBooleanSelector: {
    marginBottom: 16,
  },
  filterBooleanButtons: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  filterBooleanButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 4,
    backgroundColor: '#f0f0f0',
    borderWidth: 1,
    borderColor: '#ddd',
    alignItems: 'center',
  },
  filterBooleanButtonActive: {
    backgroundColor: '#667eea',
    borderColor: '#667eea',
  },
  filterBooleanButtonText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  filterBooleanButtonTextActive: {
    color: '#fff',
  },
  draggingHeader: {
    opacity: 0.3,
    backgroundColor: '#5568d3',
  },
  dragOverHeader: {
    backgroundColor: '#7c8ff0',
    borderLeftWidth: 3,
    borderLeftColor: '#fff',
  },
  draggingCell: {
    opacity: 0.3,
    backgroundColor: '#f0f0f0',
  },
  dragOverCell: {
    backgroundColor: '#e8f0ff',
    borderLeftWidth: 3,
    borderLeftColor: '#667eea',
  },
  headerCellTouchable: {
    flex: 1,
    width: '100%',
  },
  dragHandle: {
    color: '#fff',
    fontSize: 10,
    marginLeft: 4,
    opacity: 0.7,
  },
  dragHandleContainer: {
    padding: 4,
    marginRight: 4,
    cursor: 'grab',
    userSelect: 'none',
  },
  dragHandleIcon: {
    color: '#fff',
    fontSize: 12,
    opacity: 0.8,
    lineHeight: 12,
    marginRight: 4,
  },
  draggableHeader: {
    cursor: 'grab',
  },
  hiddenColumnsIndicator: {
    width: 40,
    backgroundColor: '#667eea',
    borderRightWidth: 1,
    borderRightColor: '#5568d3',
    justifyContent: 'center',
    alignItems: 'center',
  },
  hiddenColumnsHeader: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
  },
  hiddenColumnsText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 16,
  },
  hiddenColumnsCell: {
    width: 40,
    backgroundColor: '#fafafa',
  },
  contextMenuOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  contextMenu: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    minWidth: 150,
  },
  contextMenuItem: {
    padding: 12,
    borderRadius: 4,
  },
  contextMenuText: {
    fontSize: 14,
    color: '#333',
  },
  contextMenuSubtext: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
  },
  tableHeaderCellContainer: {
    flexDirection: 'row',
    position: 'relative',
  },
  resizeHandle: {
    width: 6,
    backgroundColor: 'rgba(102, 126, 234, 0.1)',
    cursor: 'col-resize',
    position: 'absolute',
    right: -3,
    top: 0,
    bottom: 0,
    zIndex: 10,
  },
  resizeHandleActive: {
    backgroundColor: '#667eea',
    opacity: 0.6,
  },
  cellModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    width: '90%',
    maxWidth: 600,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
  },
  cellModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  cellModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  cellModalBody: {
    padding: 20,
    maxHeight: 400,
  },
  cellModalValue: {
    fontSize: 14,
    color: '#333',
    fontFamily: 'monospace',
    lineHeight: 20,
  },
  fkLinkText: {
    color: '#667eea',
    textDecorationLine: 'underline',
  },
  focusedRow: {
    backgroundColor: '#f0f4ff',
    borderLeftWidth: 3,
    borderLeftColor: '#667eea',
  },
  focusedCell: {
    backgroundColor: '#e8f0ff',
    borderLeftWidth: 2,
    borderLeftColor: '#667eea',
  },
  fkRecordModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    width: '90%',
    maxWidth: 600,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  fkRecordModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  fkRecordModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  fkRecordModalBody: {
    padding: 20,
    maxHeight: 400,
  },
  fkRecordField: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    alignItems: 'center',
  },
  fkRecordFieldFK: {
    backgroundColor: '#f5f5f5',
    opacity: 0.7,
  },
  fkRecordFieldActive: {
    backgroundColor: '#e8f0ff',
  },
  fkRecordFieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    width: 150,
    marginRight: 16,
  },
  fkRecordFieldLabelFK: {
    color: '#999',
    fontStyle: 'italic',
  },
  fkRecordFieldLabelActive: {
    color: '#667eea',
  },
  fkRecordFieldValue: {
    fontSize: 14,
    color: '#333',
    flex: 1,
    fontFamily: 'monospace',
  },
  fkRecordFieldValueFK: {
    color: '#999',
  },
  fkRecordToggleIconButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  fkRecordToggleIconButtonAdd: {
    backgroundColor: '#9eb5d4',
  },
  fkRecordToggleIconButtonRemove: {
    backgroundColor: '#d4a5a5',
  },
  fkRecordToggleIconButtonPlaceholder: {
    width: 24,
    height: 24,
    marginRight: 8,
  },
  fkRecordToggleIconButtonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
    lineHeight: 20,
  },
  fkRecordModalFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  fkRecordViewLink: {
    alignItems: 'flex-end',
  },
  fkRecordViewLinkText: {
    color: '#667eea',
    fontSize: 16,
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
  fkHoverModal: {
    backgroundColor: '#fff',
    borderRadius: 8,
    width: 280,
    maxHeight: 300,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  fkHoverModalContent: {
    padding: 12,
    maxHeight: 280,
  },
  fkHoverModalRow: {
    flexDirection: 'row',
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  fkHoverModalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666',
    width: 80,
    marginRight: 8,
  },
  fkHoverModalValue: {
    fontSize: 12,
    color: '#333',
    flex: 1,
    fontFamily: 'monospace',
  },
  fkHoverModalText: {
    fontSize: 12,
    color: '#666',
    padding: 12,
  },
  fkHoverModalMore: {
    fontSize: 11,
    color: '#999',
    fontStyle: 'italic',
    paddingTop: 4,
    textAlign: 'center',
  },
  fkHoverModalLink: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    alignItems: 'flex-end',
  },
  fkHoverModalLinkText: {
    color: '#667eea',
    fontSize: 12,
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
  fkConfigModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    width: '95%',
    maxWidth: 900,
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  fkConfigModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  fkConfigModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  fkConfigModalBody: {
    padding: 20,
    flex: 1,
  },
  fkConfigModalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 16,
  },
  fkConfigModalSubLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 16,
  },
  fkConfigCascadingContainer: {
    flex: 1,
  },
  fkConfigCascadingContent: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  fkConfigLevelPanel: {
    width: 250,
    marginRight: 12,
    borderRightWidth: 1,
    borderRightColor: '#e0e0e0',
    paddingRight: 12,
  },
  fkConfigLevelTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#667eea',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  fkConfigLevelColumnsList: {
    maxHeight: 400,
  },
  fkConfigColumnsList: {
    maxHeight: 300,
  },
  fkConfigColumnItem: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    backgroundColor: '#fff',
  },
  fkConfigColumnItemFK: {
    backgroundColor: '#f5f5f5',
    opacity: 0.7,
  },
  fkConfigColumnItemActive: {
    backgroundColor: '#e8f0ff',
  },
  fkConfigColumnItemText: {
    fontSize: 14,
    color: '#333',
  },
  fkConfigColumnItemTextFK: {
    color: '#999',
    fontStyle: 'italic',
  },
  fkConfigColumnItemTextActive: {
    color: '#667eea',
    fontWeight: '600',
  },
  fkConfigLoadingText: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    padding: 20,
  },
  fkConfigColumnItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fkConfigColumnItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  fkConfigColumnFKIndicator: {
    fontSize: 12,
    color: '#667eea',
    fontStyle: 'italic',
    marginLeft: 8,
  },
  fkConfigToggleButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#667eea',
    borderRadius: 4,
    minWidth: 60,
    alignItems: 'center',
  },
  fkConfigToggleButtonActive: {
    backgroundColor: '#dc3545',
  },
  fkConfigToggleButtonText: {
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
  },
  fkConfigToggleButtonTextActive: {
    color: '#fff',
  },
  fkConfigCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#ccc',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  fkConfigCheckboxText: {
    fontSize: 14,
    color: '#667eea',
    fontWeight: 'bold',
  },
  fkConfigExpandButton: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  fkConfigExpandButtonText: {
    fontSize: 12,
    color: '#667eea',
  },
  fkRecordApplyButton: {
    backgroundColor: '#667eea',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 4,
    alignItems: 'center',
  },
  fkRecordApplyButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  formatConfigModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    width: '95%',
    maxWidth: 1500,
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  formatConfigModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  formatConfigModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  formatConfigModalPanels: {
    flexDirection: 'row',
    flex: 1,
    minHeight: 400,
  },
  formatConfigLeftPanel: {
    flex: 0.35,
    minWidth: 250,
    borderRightWidth: 1,
    borderRightColor: '#e0e0e0',
    flexDirection: 'column',
  },
  formatConfigRightPanel: {
    flex: 0.7,
    minWidth: 300,
    flexDirection: 'column',
  },
  formatConfigPanelTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    padding: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    backgroundColor: '#f8f9fa',
  },
  formatConfigPanelScroll: {
    flex: 1,
    padding: 16,
  },
  formatConfigModalFooter: {
    flexDirection: 'row',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    gap: 12,
    justifyContent: 'flex-end',
  },
  formatConfigNoOptions: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formatConfigNoOptionsText: {
    fontSize: 14,
    color: '#999',
    fontStyle: 'italic',
  },
  formatConfigSection: {
    marginBottom: 24,
  },
  formatConfigSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 12,
  },
  formatConfigSectionSubtitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666',
    marginBottom: 8,
    marginTop: 4,
  },
  formatConfigUnitsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  formatConfigUnitButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    minWidth: 50,
    alignItems: 'center',
  },
  formatConfigUnitButtonSelected: {
    backgroundColor: '#667eea',
    borderColor: '#667eea',
  },
  formatConfigUnitButtonText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  formatConfigUnitButtonTextSelected: {
    color: '#fff',
  },
  formatConfigOption: {
    padding: 12,
    borderRadius: 6,
    backgroundColor: '#f5f5f5',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  formatConfigOptionSelected: {
    backgroundColor: '#667eea',
    borderColor: '#667eea',
  },
  formatConfigOptionText: {
    fontSize: 14,
    color: '#333',
  },
  formatConfigOptionTextSelected: {
    color: '#fff',
    fontWeight: '500',
  },
  formatConfigInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    padding: 12,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  formatConfigToggle: {
    padding: 12,
    borderRadius: 6,
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  formatConfigToggleText: {
    fontSize: 14,
    color: '#333',
  },
  formatConfigButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 6,
    alignItems: 'center',
  },
  formatConfigClearButton: {
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  formatConfigApplyButton: {
    backgroundColor: '#667eea',
  },
  formatConfigButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  csvExportModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    width: '90%',
    maxWidth: 500,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  csvExportModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  csvExportModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  csvExportModalBody: {
    padding: 16,
  },
  csvExportModalDescription: {
    fontSize: 14,
    color: '#666',
    marginBottom: 12,
  },
  csvExportFormatSelector: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
  },
  csvExportFormatButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    backgroundColor: '#fafafa',
    alignItems: 'center',
  },
  csvExportFormatButtonSelected: {
    borderColor: '#667eea',
    backgroundColor: '#f0f4ff',
  },
  csvExportFormatButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
  },
  csvExportFormatButtonTextSelected: {
    color: '#667eea',
  },
  csvExportOption: {
    padding: 12,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    marginBottom: 12,
    backgroundColor: '#fafafa',
  },
  csvExportOptionSelected: {
    borderColor: '#667eea',
    backgroundColor: '#f0f4ff',
  },
  csvExportOptionContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  csvExportRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ccc',
    marginRight: 12,
    marginTop: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  csvExportRadioSelected: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#667eea',
  },
  csvExportOptionText: {
    flex: 1,
  },
  csvExportOptionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  csvExportOptionDescription: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },
  csvExportModalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  csvExportButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 6,
    minWidth: 100,
    alignItems: 'center',
  },
  csvExportCancelButton: {
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  csvExportDownloadButton: {
    backgroundColor: '#667eea',
  },
  csvExportButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
});
